name: build_Release
on:
  push:
    branches:
      - dev
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    name: Build with Theos
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4
      with:
          submodules: recursive

    - name: Install Theos
      uses: Randomblock1/theos-action@v1.4

    - name: Patch TrollStore
      run: |
        git clone https://github.com/wwg135/TrollStore build
        cd build
        git checkout main

        # Apply patches
        patch -p1 < ../patches/001-Shared.patch
        if [ "$?" -ne 0 ]; then
          echo "Error applying Shared patch ..."
          exit 1
        fi
        patch -p1 < ../patches/003-TrollStore.patch
        if [ "$?" -ne 0 ]; then
          echo "Error applying TrollStore patch ..."
          exit 1
        fi

        echo WORKDIR="$(pwd)" >> "$GITHUB_ENV"
        echo VERSION="1.5.1" >> "$GITHUB_ENV"
        # drop build ipa by default
        sed -i '' 's/build_installer15 build_installer64e//g' Makefile

        # Copy Localizable to Resources
        cp -a ../TrollStore/* TrollStore/Resources/

    - name: Install libarchive
      run: |
        brew install libarchive
        echo 'export PATH="/usr/local/opt/libarchive/bin:$PATH"' >> /Users/runner/.bash_profile
        export LDFLAGS="-L/usr/local/opt/libarchive/lib"
        export CPPFLAGS="-I/usr/local/opt/libarchive/include"
        export PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig"

    - name: Build TrollStore
      working-directory: ${{ env.WORKDIR }}
      run: |
        make

    - name: Upload Artifact
      id: dopamine-latest-upload
      uses: actions/upload-artifact@v4.3.2
      with:
        name: Dopamine
        path: |
          ${{ env.WORKDIR }}/_build/TrollStore.tar
